# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install: pip install -r requirements/dev.txt

script:
  - createuser localuser
  - python manage.py setup_db
  - python manage.py db upgrade
  - sh run_tests.sh 300
