branch-defaults:
  master:
    environment: Rank-dev
global:
  application_name: Rank
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-east-1
  profile: null
  sc: git
