"""empty message

Revision ID: 4e75c0ed029e
Revises: 37a45401820b
Create Date: 2015-11-04 10:52:28.915508

"""

# revision identifiers, used by Alembic.
revision = '4e75c0ed029e'
down_revision = '37a45401820b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
